search:
  ConnectionStrings: !spec
    description: List of cluster names.
    type: {}
    value:
      cluster_a: ['cluster_a_host1', 'cluster_a_host2']
      cluster_b: ['cluster_b_host1', 'cluster_b_host2']
